### ISSUE TITLE
Error while dumping large databases

### ISSUE THREAD

**Issue by hacktvist** [bradzacher/mysqldump#2]
FATAL ERROR: JS Allocation failed - process out of memory
Aborted (core dumped)

**Comment by webcaetano** [comment]
Give me more feedback about it... 

What's the size of the DB?
Are you using EJS on this?

**Comment by 57ar7up** [comment]
I have error when dumping huge DB:

mysqldump\index.js:155
                        callback(null,results.createSchemaDump.concat(results.createDataDump).join("\n\n"));
                                                                                              ^

RangeError: Invalid string length
    at Array.join (native)
    at Array.async.auto.getDataDump (node_modules\mysqldump\index.js:155:74)
    at listener (node_modules\async\lib\async.js:605:42)
    at node_modules\async\lib\async.js:544:17
    at _arrayEach (node_modules\async\lib\async.js:85:13)
    at Immediate.taskComplete (node_modules\async\lib\async.js:543:13)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
